import { getApps, getApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { getDatabase, ref, get, update, remove } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
import { ADMIN_UID } from "./firebase-config.js?v=18.1";

const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const wait=ms=>new Promise(r=>setTimeout(r,ms));

const STATUS_OPTIONS=[
  ["waiting","Oczekuje na wybór"],
  ["selected","Wybór zatwierdzony"],
  ["editing","W obróbce"],
  ["ready","Gotowe"],
  ["delivered","Dostarczone"]
];
const STATUS_LABELS=Object.fromEntries(STATUS_OPTIONS);

const TEMPLATES={
  wedding:{name:"Ślub / narzeczeńska",icon:"♥",subtitle:"Wybierzcie swoje ulubione kadry ❤️",intro:"Wasza prywatna galeria jest gotowa. Miłego oglądania!",outro:"Dziękuję za zaufanie. Niech te kadry zostaną z Wami na lata ❤️",uiConfig:{desktopColumns:4,tabletColumns:3,mobileColumns:2,gridGap:8,mobileGridGap:7,cardRadius:10,mobileCardRadius:9,heartColor:"#ff3b4d",heroLayout:"trio",heroFit:"cover",heroOverlay:44,heroTileGap:4,heroTileRadius:5},presentationConfig:{interval:5}},
  family:{name:"Rodzinna",icon:"⌂",subtitle:"Wasza rodzinna historia w kadrach",intro:"Cieszę się, że mogę oddać Wam tę rodzinną pamiątkę ❤️",outro:"Dziękuję za wspólnie spędzony czas i mnóstwo naturalnych emocji.",uiConfig:{desktopColumns:4,tabletColumns:3,mobileColumns:2,gridGap:10,mobileGridGap:8,cardRadius:16,mobileCardRadius:13,heartColor:"#ff5d6c",heroLayout:"duo",heroFit:"cover",heroOverlay:38,heroTileGap:6,heroTileRadius:14},presentationConfig:{interval:6}},
  christening:{name:"Chrzest / komunia",icon:"✦",subtitle:"Najpiękniejsze momenty tego wyjątkowego dnia",intro:"Galeria jest gotowa — zapraszam do spokojnego obejrzenia i wyboru zdjęć.",outro:"Dziękuję za możliwość uwiecznienia tego ważnego dnia.",uiConfig:{desktopColumns:4,tabletColumns:3,mobileColumns:2,gridGap:10,mobileGridGap:8,cardRadius:12,mobileCardRadius:10,heartColor:"#e9d8a6",heroLayout:"trio",heroFit:"cover",heroOverlay:34,heroTileGap:5,heroTileRadius:10},presentationConfig:{interval:6}},
  corporate:{name:"Firmowa / biznesowa",icon:"▦",subtitle:"Materiały z sesji firmowej",intro:"Prywatna galeria materiałów jest gotowa do przeglądania.",outro:"Dziękuję za współpracę z RAF.studio.",uiConfig:{desktopColumns:5,tabletColumns:4,mobileColumns:2,gridGap:6,mobileGridGap:6,cardRadius:4,mobileCardRadius:4,heartColor:"#4ea5ff",heroLayout:"single",heroFit:"cover",heroOverlay:55,heroTileGap:0,heroTileRadius:0},presentationConfig:{interval:4}},
  event:{name:"Event",icon:"▶",subtitle:"Galeria z wydarzenia",intro:"Zdjęcia z wydarzenia są już gotowe — zapraszam do galerii.",outro:"Dziękuję za współpracę i do zobaczenia na kolejnym wydarzeniu!",uiConfig:{desktopColumns:5,tabletColumns:4,mobileColumns:2,gridGap:6,mobileGridGap:5,cardRadius:8,mobileCardRadius:7,heartColor:"#ff3b4d",heroLayout:"mosaic4",heroFit:"cover",heroOverlay:48,heroTileGap:3,heroTileRadius:4},presentationConfig:{interval:4}}
};

let app,auth,db;
let galleries={};
let refreshTimer=null;
let observer=null;
let started=false;
let pendingTemplateKey="";

function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
function fmtTime(v){const n=Number(v||0);if(!n)return"—";try{return new Intl.DateTimeFormat("pl-PL",{dateStyle:"short",timeStyle:"short"}).format(new Date(n));}catch{return"—";}}
function sum(list,key){return list.reduce((a,x)=>a+Number(x?.[key]||0),0);}

async function waitForApp(){for(let i=0;i<160;i++){if(getApps().length)return getApp();await wait(25);}return null;}

function toast(message){const old=$("#rafV181Toast");old?.remove();const el=document.createElement("div");el.id="rafV181Toast";el.textContent=message;el.style.cssText="position:fixed;z-index:120000;left:50%;bottom:24px;transform:translateX(-50%);padding:11px 14px;border-radius:12px;background:#f4f4f1;color:#111;font:800 12px system-ui;box-shadow:0 16px 55px #0009;max-width:min(92vw,560px);text-align:center";document.body.appendChild(el);setTimeout(()=>el.remove(),3200);}

function injectStyles(){if($("#rafV181Styles"))return;const s=document.createElement("style");s.id="rafV181Styles";s.textContent=`
#rafV181TemplatesDialog,#rafV181ActivityDialog{width:min(1040px,calc(100% - 18px));max-height:90vh;padding:0;border:1px solid #34343a;border-radius:20px;background:#111113;color:#f4f4f2}#rafV181TemplatesDialog::backdrop,#rafV181ActivityDialog::backdrop{background:#000c;backdrop-filter:blur(7px)}
.raf-v181-head{display:flex;align-items:flex-start;gap:14px;padding:20px;border-bottom:1px solid #29292f}.raf-v181-head h2{margin:3px 0 5px;font-size:28px}.raf-v181-head p{margin:0;color:#8d8d95;font-size:12px}.raf-v181-head .spacer{flex:1}.raf-v181-close{width:40px;height:40px;border:1px solid #34343a;border-radius:11px;background:#17171a;color:#fff;font-size:20px}
.raf-v181-body{padding:16px 20px 20px}.raf-v181-template-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px}.raf-v181-template{padding:16px;border:1px solid #2d2d33;border-radius:15px;background:#151518;cursor:pointer;text-align:left;color:#fff}.raf-v181-template:hover{border-color:#666}.raf-v181-template b{display:block;font-size:14px;margin:8px 0 5px}.raf-v181-template small{color:#8d8d95;line-height:1.35}.raf-v181-template-icon{font-size:22px}
.raf-v181-picker{margin:12px 0;padding:12px;border:1px solid #303036;border-radius:14px;background:#141417}.raf-v181-picker-row{display:flex;gap:8px;align-items:end;flex-wrap:wrap}.raf-v181-picker label{min-width:220px;flex:1}.raf-v181-picker select{width:100%}
.raf-v181-card-tools{display:flex;gap:6px;align-items:center;flex-wrap:wrap;margin-top:7px}.raf-v181-status-select{min-width:150px;padding:7px 9px;border:1px solid #34343a;border-radius:10px;background:#151518;color:#fff;font-size:10px}.raf-v181-comment-badge{padding:6px 8px;border:1px solid #59492a;border-radius:9px;background:#1c180f;color:#ffd88c;font-size:10px;font-weight:800}
.raf-v181-list{display:grid;gap:10px}.raf-v181-row{display:grid;grid-template-columns:minmax(180px,1.1fr) repeat(6,minmax(80px,.65fr));gap:8px;align-items:stretch;padding:12px;border:1px solid #2d2d32;border-radius:14px;background:#151518}.raf-v181-main{padding:7px}.raf-v181-main strong{display:block;font-size:14px}.raf-v181-main small{display:block;color:#888;margin-top:4px}.raf-v181-metric{padding:8px;border:1px solid #29292e;border-radius:10px;background:#111113}.raf-v181-metric span{display:block;color:#85858d;font-size:9px;text-transform:uppercase;letter-spacing:.05em}.raf-v181-metric b{display:block;font-size:15px;margin-top:4px}.raf-v181-comment{grid-column:1/-1;padding:9px 11px;border-left:3px solid #7a6532;background:#18160f;border-radius:8px;color:#dcd2b7;font-size:11px}.raf-v181-actions{grid-column:1/-1;display:flex;gap:8px;justify-content:flex-end}
@media(max-width:900px){.raf-v181-template-grid{grid-template-columns:repeat(2,1fr)}.raf-v181-row{grid-template-columns:repeat(2,1fr)}.raf-v181-main{grid-column:1/-1}}@media(max-width:560px){.raf-v181-template-grid{grid-template-columns:1fr}.raf-v181-row{grid-template-columns:1fr}}
`;document.head.appendChild(s);}

function injectHeaderButtons(){const actions=$(".admin-head-actions");if(!actions)return;if(!$("#rafV181TemplatesBtn")){const b=document.createElement("button");b.id="rafV181TemplatesBtn";b.type="button";b.className="ghost";b.textContent="🧩 Szablony";actions.insertBefore(b,$("#newGalleryBtn")||null);b.onclick=()=>$("#rafV181TemplatesDialog")?.showModal();}if(!$("#rafV181ActivityBtn")){const b=document.createElement("button");b.id="rafV181ActivityBtn";b.type="button";b.className="ghost";b.textContent="📊 Aktywność";actions.insertBefore(b,$("#newGalleryBtn")||null);b.onclick=async()=>{await renderActivity();$("#rafV181ActivityDialog")?.showModal();};}}

function injectDialogs(){
if(!$("#rafV181TemplatesDialog"))document.body.insertAdjacentHTML("beforeend",`<dialog id="rafV181TemplatesDialog"><div class="raf-v181-head"><div><small class="eyebrow">PRESETY RAF.STUDIO</small><h2>Szablony galerii</h2><p>Gotowe ustawienia dla najczęstszych rodzajów sesji.</p></div><span class="spacer"></span><button class="raf-v181-close" data-v181-close="rafV181TemplatesDialog">×</button></div><div class="raf-v181-body"><div class="raf-v181-template-grid">${Object.entries(TEMPLATES).map(([key,t])=>`<button type="button" class="raf-v181-template" data-v181-template="${key}"><span class="raf-v181-template-icon">${t.icon}</span><b>${esc(t.name)}</b><small>${esc(t.subtitle)}</small></button>`).join("")}</div></div></dialog>`);
if(!$("#rafV181ActivityDialog"))document.body.insertAdjacentHTML("beforeend",`<dialog id="rafV181ActivityDialog"><div class="raf-v181-head"><div><small class="eyebrow">KLIENCI</small><h2>Aktywność i statystyki</h2><p>Dane są pobierane dopiero po otwarciu tego okna — panel admina nie jest obciążany w tle.</p></div><span class="spacer"></span><button class="raf-v181-close" data-v181-close="rafV181ActivityDialog">×</button></div><div class="raf-v181-body"><div id="rafV181ActivityList" class="raf-v181-list"><div class="notice">Kliknij Aktywność, aby wczytać dane.</div></div></div></dialog>`);
$$('[data-v181-close]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound="1";b.onclick=()=>$("#"+b.dataset.v181Close)?.close();});
$$('[data-v181-template]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound="1";b.onclick=()=>chooseTemplate(b.dataset.v181Template);});
}

function injectTemplatePicker(){const form=$("#galleryForm");if(!form||$("#rafV181TemplatePicker"))return;const box=document.createElement("div");box.id="rafV181TemplatePicker";box.className="raf-v181-picker";box.innerHTML=`<div class="raf-v181-picker-row"><label>Szablon galerii<select id="rafV181TemplateSelect"><option value="">— wybierz —</option>${Object.entries(TEMPLATES).map(([k,t])=>`<option value="${k}">${esc(t.name)}</option>`).join("")}</select></label><button id="rafV181ApplyTemplate" type="button" class="ghost">Zastosuj szablon</button></div>`;form.querySelector(".dialog-head")?.insertAdjacentElement("afterend",box);$("#rafV181ApplyTemplate").onclick=()=>{const key=$("#rafV181TemplateSelect").value;if(key)applyTemplate(key,true);};form.addEventListener("submit",()=>{if(pendingTemplateKey)scheduleTemplateSave(pendingTemplateKey);},true);}
function setVal(id,v){const el=$("#"+id);if(el&&v!==undefined)el.value=v;}
function applyTemplate(key,persistIfEditing=false){const t=TEMPLATES[key];if(!t)return;pendingTemplateKey=key;setVal("gallerySubtitleInput",t.subtitle);setVal("introMessageInput",t.intro);setVal("outroMessageInput",t.outro);const slug=$("#editingSlug")?.value?.trim();if(persistIfEditing&&slug){update(ref(db,`galleries/${slug}/public`),{uiConfig:t.uiConfig,presentationConfig:t.presentationConfig,templateKey:key,updatedAt:Date.now()}).then(()=>{toast(`Zastosowano szablon: ${t.name}`);refreshGalleries();}).catch(e=>toast(`Błąd szablonu: ${e.message||e}`));}else toast(`Szablon „${t.name}” wczytany do formularza`);}
function chooseTemplate(key){$("#rafV181TemplatesDialog")?.close();if(!$("#galleryDialog")?.open)$("#newGalleryBtn")?.click();setTimeout(()=>{if($("#rafV181TemplateSelect"))$("#rafV181TemplateSelect").value=key;applyTemplate(key,false);},120);}
function scheduleTemplateSave(key){const t=TEMPLATES[key];if(!t)return;const slug=String($("#gallerySlugInput")?.value||"").trim();if(!slug)return;pendingTemplateKey="";(async()=>{for(let i=0;i<10;i++){await wait(500);try{const snap=await get(ref(db,`galleries/${slug}/public`));if(!snap.exists())continue;await update(ref(db,`galleries/${slug}/public`),{uiConfig:t.uiConfig,presentationConfig:t.presentationConfig,templateKey:key,updatedAt:Date.now()});toast(`Nowa galeria otrzymała szablon: ${t.name}`);break;}catch{}}})();}

async function refreshGalleries(){if(!db)return;try{const snap=await get(ref(db,"galleries"));galleries=snap.val()||{};decorateCards();}catch(e){console.warn("RAF v18.1 galleries refresh failed",e);}}
function scheduleRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(refreshGalleries,180);}

function getStatus(pub){return typeof pub?.workflowStatus==="string"?pub.workflowStatus:(pub?.workflowStatus?.key||"waiting");}
function decorateCards(){const list=$("#galleryList");if(!list)return;$$('.gallery-card',list).forEach(card=>{const slug=$("[data-upload]",card)?.dataset.upload||$("[data-copy]",card)?.dataset.copy;if(!slug)return;const pub=galleries?.[slug]?.public||{};const status=getStatus(pub);const signature=`${slug}|${status}`;let row=$(".raf-v181-card-tools",card);if(!row){row=document.createElement("div");row.className="raf-v181-card-tools";($(".gallery-body",card)||card).appendChild(row);}if(row.dataset.signature===signature)return;row.dataset.signature=signature;row.innerHTML=`<select class="raf-v181-status-select" data-v181-status="${esc(slug)}" title="Status widoczny dla klienta">${STATUS_OPTIONS.map(([k,label])=>`<option value="${k}" ${k===status?"selected":""}>${esc(label)}</option>`).join("")}</select>`;$("[data-v181-status]",row).onchange=e=>saveStatus(slug,e.target.value);});}
async function saveStatus(slug,key){const label=STATUS_LABELS[key]||STATUS_LABELS.waiting;try{await update(ref(db,`galleries/${slug}/public`),{workflowStatus:{key,label,updatedAt:Date.now()},updatedAt:Date.now()});if(galleries?.[slug]?.public)galleries[slug].public.workflowStatus={key,label,updatedAt:Date.now()};decorateCards();toast(`Status: ${label}`);}catch(e){toast(`Nie udało się zapisać statusu: ${e.message||e}`);}}

function latestApproval(all,slug){const items=Object.values(all?.[slug]||{}).filter(x=>x&&x.mode!=="rejected"&&Number(x.submittedAt||0)>0).sort((a,b)=>Number(b.submittedAt)-Number(a.submittedAt));return items[0]||null;}
function aggregateStats(all,slug){const clients=Object.values(all?.[slug]||{}).filter(Boolean);const viewed=new Set();clients.forEach(c=>Object.values(c.viewed||{}).forEach(v=>{if(v?.filename)viewed.add(v.filename);}));const last=Math.max(0,...clients.map(c=>Number(c.lastOpenedAt||c.lastActivityAt||0)));return{clients:clients.length,visits:sum(clients,"visits"),viewed:viewed.size,downloads:sum(clients,"downloadsTotal"),full:sum(clients,"fullGalleryDownloads"),presentation:sum(clients,"presentationStarts"),last};}

async function renderActivity(){const list=$("#rafV181ActivityList");if(!list)return;list.innerHTML='<div class="notice">Ładowanie statystyk…</div>';let approvals={},analytics={};try{const [gSnap,aSnap]=await Promise.all([get(ref(db,"galleries")),get(ref(db,"approvals"))]);galleries=gSnap.val()||{};approvals=aSnap.val()||{};}catch(e){list.innerHTML=`<div class="notice error-box">Nie udało się pobrać danych: ${esc(e.message||e)}</div>`;return;}try{const anSnap=await get(ref(db,"clientAnalytics"));analytics=anSnap.val()||{};}catch{analytics={};}
const rows=Object.entries(galleries).filter(([slug,g])=>!slug.startsWith("__system__")&&g?.public&&!g.public.trashedAt).sort((a,b)=>String(a[1].public.title||a[0]).localeCompare(String(b[1].public.title||b[0]),"pl",{numeric:true}));if(!rows.length){list.innerHTML='<div class="notice">Brak galerii.</div>';return;}
list.innerHTML=rows.map(([slug,g])=>{const pub=g.public||{};const st=aggregateStats(analytics,slug);const ap=latestApproval(approvals,slug);const comment=String(ap?.comment||"").trim();const status=getStatus(pub);return `<div class="raf-v181-row"><div class="raf-v181-main"><strong>${esc(pub.title||slug)}</strong><small>Ostatnio: ${esc(fmtTime(st.last))} • ${st.clients} urządzeń</small></div><div class="raf-v181-metric"><span>Wejścia</span><b>${st.visits}</b></div><div class="raf-v181-metric"><span>Obejrzane</span><b>${st.viewed}</b></div><div class="raf-v181-metric"><span>Pobrania</span><b>${st.downloads}</b></div><div class="raf-v181-metric"><span>Cała galeria</span><b>${st.full}</b></div><div class="raf-v181-metric"><span>Prezentacje</span><b>${st.presentation}</b></div><div class="raf-v181-metric"><span>Wybrano</span><b>${Number(ap?.selectedCount||0)}</b></div>${comment?`<div class="raf-v181-comment"><b>💬 Komentarz do wyboru:</b> ${esc(comment)}</div>`:""}<div class="raf-v181-actions"><select class="raf-v181-status-select" data-v181-activity-status="${esc(slug)}">${STATUS_OPTIONS.map(([k,label])=>`<option value="${k}" ${k===status?"selected":""}>${esc(label)}</option>`).join("")}</select><button type="button" class="ghost" data-v181-clear="${esc(slug)}">Wyczyść statystyki</button></div></div>`;}).join("");
$$('[data-v181-activity-status]',list).forEach(el=>el.onchange=()=>saveStatus(el.dataset.v181ActivityStatus,el.value));$$('[data-v181-clear]',list).forEach(b=>b.onclick=async()=>{const slug=b.dataset.v181Clear;if(!confirm(`Wyczyścić statystyki galerii „${galleries?.[slug]?.public?.title||slug}”?`))return;try{await remove(ref(db,`clientAnalytics/${slug}`));toast("Statystyki wyczyszczone");await renderActivity();}catch(e){toast(`Błąd: ${e.message||e}`);}});}

function installSafeObserver(){const list=$("#galleryList");if(!list||observer)return;observer=new MutationObserver(mutations=>{if(mutations.some(m=>m.type==="childList"))scheduleRefresh();});observer.observe(list,{childList:true,subtree:false});}

async function start(){if(started)return;started=true;injectStyles();injectDialogs();injectHeaderButtons();injectTemplatePicker();app=await waitForApp();if(!app)return;auth=getAuth(app);db=getDatabase(app);onAuthStateChanged(auth,user=>{if(!user||user.uid!==ADMIN_UID)return;injectHeaderButtons();injectTemplatePicker();installSafeObserver();refreshGalleries();});}
start().catch(e=>console.warn("RAF admin premium v18.1 failed",e));
